---
BESMAN_ORG: Be-Secure
BESMAN_OSSP: tomcat
BESMAN_OSSP_CLONE_PATH: $HOME/$BESMAN_OSSP
BESMAN_ANSIBLE_ROLES_PATH: $BESMAN_DIR/tmp/$BESMAN_OSSP/roles
BESMAN_ANSIBLE_ROLES: asa1997/ansible-role-oah-java,asa1997/ansible-role-oah-maven,asa1997/ansible-role-oah-eclipse
BESMAN_OSS_TRIGGER_PLAYBOOK_PATH: $BESMAN_DIR/tmp/$BESMAN_OSSP
BESMAN_OSS_TRIGGER_PLAYBOOK: besman-$BESMAN_OSSP-BT-trigger-playbook.yaml
BESMAN_DISPLAY_SKIPPED_ANSIBLE_HOSTS: false
openjdk_version: 8
java_tmp: "$HOME/java_tmp"
mvn_tmp: "$HOME/mvn_tmp"
eclipse_req_packages: snapd
eclipse_tmp: "$HOME/eclipse_tmp"
eclipse_pin_fav: false
